platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Swiftilities_Example' do
  pod 'Swiftilities', :path => '../'
end

target 'Swiftilities_Tests' do
  pod 'Swiftilities', :path => '../'
end
