disabled_rules:
  - comma
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - todo
  - type_body_length
  - variable_name
  - valid_docs

type_name:
  min_length: 2

variable_name:
    excluded:
        - URL

statement_position:
  statement_mode: uncuddled_else

excluded:
  - Pods
